export const FETCH_POSTS = 'FETCH_POSTS';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const FETCH_MESSAGES = 'FETCH_MESSAGES';
export const FETCH_COMMENTS = 'FETCH COMMENTS';
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const PAGE_LOADED = 'PAGE_LOADED';
